version: '3'

services:
  db:
    image: mysql/mysql-server:8.0.20
    environment:
      - MYSQL_PASSWORD=jMetalroot
      - MYSQL_ROOT_PASSWORD=jMetalroot
      - MYSQL_DATABASE=jMetal_database
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306

  jmetal-webPage-App:
    image: harenderdhanoya/jmetal-webpage:1.0
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "jmetal-webPage-0.1.0.jar"]
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    ports:
      - 8080:8080